# Generated by Django 2.0.6 on 2018-07-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_remove_choice4_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice4',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
